CREATE TABLE comuni_italiani (
    id                  INT AUTO_INCREMENT PRIMARY KEY,
    codice_regione      TINYINT,
    codice_sovracom     SMALLINT,
    codice_prov_storico SMALLINT,
    progressivo         SMALLINT,
    codice_alfanum      VARCHAR(10),
    nome_bilingue       VARCHAR(150),
    nome                VARCHAR(150),
    nome_altra_lingua   VARCHAR(150),
    codice_ripartizione TINYINT,
    ripartizione        VARCHAR(20),
    nome_regione        VARCHAR(60),
    nome_provincia      VARCHAR(100),
    tipo_sovracom       TINYINT,
    capoluogo           TINYINT(1),
    sigla_provincia     CHAR(2),
    codice_comune       INT,
    codice_com_110      INT,
    codice_com_107      INT,
    codice_com_103      INT,
    codice_catastale    CHAR(4),
    nuts1_2021          VARCHAR(10),
    nuts2_2021          VARCHAR(10),
    nuts3_2021          VARCHAR(10),
    nuts1_2024          VARCHAR(10),
    nuts2_2024          VARCHAR(10),
    nuts3_2024          VARCHAR(10)
);
